### PR TITLE
Update grammar_dataset_process.ipynb 

### PR DESCRIPTION
**Pull request by anshikavermag**
# What does this PR do?
Fixes a typo in the ''grammar_dataset_process.ipynb''.
Removes the repeated (" v\", _\"**n't**_\"), and adds  (\" v\", **_\"v\"_**),  to be applicable for any 'v' belonging to                   { v: v is a non case-sensitive alphabet }

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
      Pull Request section?  YES
- [ ] Did you make sure to update the documentation with your changes?  NO

### CODE REVIEW

**Comment by anshikavermag** [comment]
Hi everyone,
Four months ago, as a newcomer to open source, I stumbled upon a small typo in the llma2 grammar dataset.
I promptly fixed it only in my own repository, completely unaware that creating a PR was the way to go to get this improvement merged into the original code. So I've now created a PR. 
I'm open to any communication, corrections, or discussions related to the change. I'm here to learn and contribute!

Looking forward to your feedback and guidance.

**Comment by HamidShojanazeri** [comment]
@anshikavermag thanks for the PR, can you please fix the conflict and we merge it.

**Comment by anshikavermag** [comment]
please give me the 'write access'.
Thanks

**Comment by mreso** [comment]
Hi, thank you for your contribution. I'll close this PR as you already submitted the same fix in this [PR](https://github.com/facebookresearch/llama-recipes/pull/9/). Thanks again and looking forward to more contributions!

**Pull request closed without merging**
